accounts/urls.py
from django.conf.urls import patterns, include, url
import views


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'wordstat.views.home', name='home'),
    url(r'^expired/$', views.ListofExpiredView.as_view(), name='list_of_expired'),
    url(r'^promo-code/(?P<promo_code>\w+)/$', views.PromoCodeUpgradeAccountView.as_view(), name='promo_code_account_upgrade'),
    url(r'^generate-promo-code/$', views.generate_promo_code, name='generate_promo_code'),
)

wordstat/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'wordstat.views.home', name='home'),
    url(r'^sign-up/$', 'accounts.views.sign_up_test_view', name='sign-up'),
    url(r'^accounts/', include('accounts.urls')),
	url(r'^site/', include('sites2check.views')),
    url(r'^imperavi/', include('imperavi.urls')),
    # url(r'^newsletter/', include('newsletter.urls')),
    url(r'^admin/django-ses/', include('django_ses.urls')),
    url(r'^admin/', include(admin.site.urls)),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sites2check/forms.py
#-*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django import forms
from sites2check.models import *
from regions.models import *
import datetime

from include.xlwt.Style import colour_map


class SiteForm(forms.ModelForm):
    def clean(self):
        self.cleaned_data['host'] = self.cleaned_data.get('host','').strip()
        return self.cleaned_data

    class Meta:
        model = Site2Check
        fields = ('host',)
        
        

class SiteBulkForm(forms.Form):
    sites = forms.CharField(label='Сайты', help_text='Список сайтов, по одному на каждую строку',
                            widget=forms.Textarea)
    
    def clean_sites(self):
        sites = self.cleaned_data.get('sites','')
        if len( sites.split('\n') ) > 10000:
            raise forms.ValidationError(u'Слишком большое число сайтов')
        return sites



class QueryForm(forms.ModelForm):
    region_str = forms.CharField(label='Регион по Яндексу', required=False, help_text='Введите первые цифры региона (оставьте пустым, если запрос не имеет геотаргетинга)')
    
    def __init__(self,**kwrds):
        """
        подставляем название региона в поле
        """
        super(QueryForm,self).__init__(**kwrds)
        if 'instance' in kwrds:
            if kwrds['instance'].region:
                self.fields['region_str'].initial = kwrds['instance'].region.title_ru
            else:
                self.fields['region_str'].initial = ''
    
    def clean_hilite_color(self):
		color = self.cleaned_data['hilite_color'].strip()
		if color and color not in colour_map.keys():
				valid_colors = ''
				for valid_color in colour_map.keys():
						valid_colors += '%s, ' % valid_color
				raise forms.ValidationError(u'Недопустимое название цвета. Допустимые: %s' % valid_colors)
		return color
        
    def clean(self):
        region_str = self.cleaned_data.get('region_str','').strip()
        if region_str:
            try: region = Region.objects.get(title_ru=region_str)
            except: raise forms.ValidationError(u'Неправильный регион')
        self.cleaned_data['query'] = self.cleaned_data.get('query','').strip()
        return self.cleaned_data

    class Meta:
        model = Query
        fields = ('query', 'region_str', 'google_region', 'hilite_color',)



class EditQueryBulkForm(forms.Form):
    queries = forms.CharField(label='Запросы', help_text='По одному запросу на каждую строку', widget=forms.Textarea)


class DatesForm(forms.Form):
        date_from = forms.DateField(('%d/%m/%Y',), label='От', initial=datetime.datetime.now()-datetime.timedelta(days=1), widget=forms.DateTimeInput(format='%d/%m/%Y', attrs={'class':'input','readonly':'readonly','size':'7'}))
        date_to = forms.DateField(('%d/%m/%Y',), label='До', initial=datetime.datetime.now(), widget=forms.DateTimeInput(format='%d/%m/%Y', attrs={'class':'input','readonly':'readonly','size':'7'}))

sites2check/views.py
#-*- coding: utf-8 -*-

from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render_to_response, get_object_or_404
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from sites2check.models import *
from sites2check.forms import *

from wordstat.decorators import *

import wordstat.settings
import os,sys,datetime,random,string

import json

from include import xlwt
from django.template.defaultfilters import striptags

@url(r'^$')
@render_to('brief_page.html')
@login_required
def brief_page(request):
    sites = request.user.user_sites.all()
    return {'sites':sites,}


@url(r'^add/$')
@render_to('add_site.html')
@login_required
def add_site(request):
    if request.method == 'POST':
        form = SiteForm(data=request.POST)
        if form.is_valid():
            nu_site = form.save(commit=False)
            nu_site.user = request.user
            if nu_site.host.startswith('http://'): nu_site.host = nu_site.host.replace('http://','')
            if nu_site.host.endswith('/'): nu_site.host = nu_site.host[0:-1]
            nu_site.host = nu_site.host.strip()
            nu_site.save()
            return HttpResponseRedirect('/site/%s/' % nu_site.host )
        else:
            return {'form':form,}
    else:
        form = SiteForm()
    return {'form':form,}


@url(r'^(.+)/edit/$')
@render_to('edit_site.html')
@login_required
def edit_site(request, host):
    site = get_object_or_404(Site2Check, host=host, user=request.user)
    if request.method == 'POST':
        form = SiteForm(instance=site, data=request.POST)
        if form.is_valid():
            site = form.save(commit=False)
            site.user = request.user
            if site.host.startswith('http://'): site.host = site.host.replace('http://','')
            if site.host.endswith('/'): site.host = site.host[0:-1]
            site.host = site.host.strip()
            site.save()
            return HttpResponseRedirect('/site/%s/' % site.host )
        else:
            return {'form':form, 'site':site, }
    else:
        form = SiteForm(instance=site)
    return {'form':form, 'site':site, }



@url(r'^(.+)/delete-site/$')
@login_required
def delete_site(request, host):
    if not request.is_ajax(): return HttpResponse('only ajax requests')
    if not request.user.is_authenticated(): return HttpResponse('only authorized users')
    site = get_object_or_404(Site2Check, host=host, user=request.user)
    site.delete()
    return HttpResponse('ok')



@url(r'^(.+)/add-query/$')
@render_to('add_query.html')
@login_required
def add_query(request, host):
    site = get_object_or_404(Site2Check, host=host, user=request.user)

    if request.method == 'POST':
        form = QueryForm(data=request.POST)
        if form.is_valid():
            if site.site_queries.all().count() + 1 > \
                    site.user.profile.account.limit_for_keywords_monitoring:
                return HttpResponse('Too many queries. Try upgrading your account.')
            nu_query = form.save(commit=False)
            nu_query.site = site
            if form.cleaned_data.get('region_str',''):
                nu_query.region = Region.objects.get(title_ru=form.cleaned_data.get('region_str',''))
            else:
                nu_query.region = None
            nu_query.save()
            return HttpResponseRedirect('/site/%s/' % site.host )
        else:
            return {'form':form, 'site':site, }
    else:
        form = QueryForm()
    return {'form':form, 'site':site,}


@url(r'^(.+)/edit-query-bulk/$')
@render_to('edit_query_bulk.html')
@login_required
def edit_query_bulk(request, host):
    site = get_object_or_404(Site2Check, host=host, user=request.user)
    current_queries = site.serializeAllQueries()
    if request.method == 'POST':
        form = EditQueryBulkForm(data=request.POST)
        if form.is_valid():
            site.site_queries.all().delete()
            for q in form.cleaned_data.get('queries','').split('\n'):
                q = q.strip()
                if len(q) < 2: continue
                if site.site_queries.all().count() > \
                        site.user.profile.account.limit_for_keywords_monitoring:
                    return HttpResponse('Too many queries. Try upgrading your account.')
                Query(site=site, query=q).save()

            return HttpResponseRedirect('/site/%s/' % site.host )
        else:
            return {'form':form, 'site':site,}
    else:
        form = EditQueryBulkForm(initial={'queries':current_queries},)
    return {'form':form, 'site':site,}





@url(r'^(.+)/edit-query/([0-9]+)/$')
@render_to('edit_query.html')
@login_required
def edit_query(request, host, query_pk):
    site = get_object_or_404(Site2Check, host=host, user=request.user)
    query = get_object_or_404(Query, pk=query_pk, site=site)
    if request.method == 'POST':
        form = QueryForm(instance=query, data=request.POST)
        if form.is_valid():
            old_query_text = query.query
            old_region = query.region
            query = form.save(commit=False)
            if form.cleaned_data.get('region_str',''):
                query.region = Region.objects.get(title_ru=form.cleaned_data.get('region_str',''))
            else:
                query.region = None
            if form.cleaned_data['query'] != old_query_text or old_region != query.region:
                query.wordstat_popularity = None # reset wordstat popularity if query text has changed
            query.save()
            return HttpResponseRedirect('/site/%s/' % site.host )
        else:
            return {'form':form, 'site':site, 'query':query,}
    else:
        form = QueryForm(instance=query)
    return {'form':form, 'site':site, 'query':query,}


@url(r'^(.+)/delete-query/$')
@login_required
def delete_query(request, host):
    if not request.is_ajax(): return HttpResponse('only ajax requests')
    if not request.user.is_authenticated(): return HttpResponse('only authorized users')
    site = get_object_or_404(Site2Check, host=host, user=request.user)
    query_pk = request.POST.get('query_pk','')
    if not query_pk: return HttpResponse('specify query pk')
    query = get_object_or_404(Query, pk=query_pk, site=site)
    query.delete()
    return HttpResponse('ok')




@url(r'^(.+)/csv/$')
@login_required
def site_positions_view_csv(request, host):
    site = get_object_or_404(Site2Check, host=host, user=request.user)
    csv = render_to_string( 'positions.csv', { 'site': site }, context_instance=RequestContext(request) )
    return HttpResponse(csv, mimetype='text/csv')




@url(r'^(.+)/guest-(.+)/xls/$')
def site_positions_export_xls_guest(request, host, pwd):
    site = get_object_or_404(Site2Check, host=host)
    date_from = request.GET.get('date_from','')
    date_to = request.GET.get('date_to','')

    # check password
    if pwd != site.getHashPass(): return HttpResponse('Неверный пароль')

    # redirect with date parameters (today\yesterday) if needed
    if not date_from or not date_to:
        return HttpResponse('Ошибка: Дата 1 и Дата 2 не выбраны')

    queries = site.site_queries.all()
    queries_list = []

    try:
        date_from = datetime.datetime.strptime(date_from, '%d/%m/%Y')
        date_to = datetime.datetime.strptime(date_to, '%d/%m/%Y')
    except:
        return HttpResponse(u'Неверный формат дат')


    if date_from > date_to: return HttpResponse('Дата 1 должна быть меньше или равна Дате 2')

    bookname = export_to_xls(site=site, date_from=date_from, date_to=date_to)

    return HttpResponseRedirect(os.path.join(settings.MEDIA_URL, 'site-reports-xls', bookname))



@url(r'^(.+)/xls/$')
@login_required
def site_positions_export_xls(request, host):
    site = get_object_or_404(Site2Check, host=host, user=request.user)
    date_from = request.GET.get('date_from','')
    date_to = request.GET.get('date_to','')

    # redirect with date parameters (today\yesterday) if needed
    if not date_from or not date_to:
        return HttpResponse('Ошибка: Дата 1 и Дата 2 не выбраны')

    queries = site.site_queries.all()
    queries_list = []

    try:
        date_from = datetime.datetime.strptime(date_from, '%d/%m/%Y')
        date_to = datetime.datetime.strptime(date_to, '%d/%m/%Y')
    except:
        return HttpResponse(u'Неверный формат дат')


    if date_from > date_to: return HttpResponse('Дата 1 должна быть меньше или равна Дате 2')

    bookname = export_to_xls(site=site, date_from=date_from, date_to=date_to)

    return HttpResponseRedirect(os.path.join(settings.MEDIA_URL, 'site-reports-xls', bookname))



@url(r'^add-bulk/$')
@render_to('add_site_bulk.html')
@login_required
def add_site_bulk(request):
    if request.method == 'POST':
        form = SiteBulkForm(data=request.POST)
        if form.is_valid():
            site_list = form.cleaned_data.get('sites','').split('\n')
            for host in site_list:
                if host.startswith('http://'): host = host.replace('http://','')
                if host.startswith('www.'): host = host.replace('www.','')
                if host.endswith('/'): host = host[0:-1]
                host = host.strip()
                if not host: continue
                try:
                    site, is_created = Site2Check.objects.get_or_create(user=request.user, host=host)
                except:
                    return HttpResponse(u'Ошибка добавления сайта. Свяжитесь с администрацией ресурса.')
                if not is_created: continue
                site.save()
            return HttpResponseRedirect('/site/' )
        else:
            return {'form':form,}
    else:
        form = SiteBulkForm()
    return {'form':form,}



@url(r'^(.+)/guest-(.+)/$')
@render_to('positions_guest.html')
def site_positions_view_guest(request, host, pwd):
    start = datetime.datetime.now()

    matching_sites = Site2Check.objects.filter(host=host)

sites2check/templates/add_query.html
{% extends 'base.html' %}


{% block path %}
    <a href='/'>Главная</a> → <a href='/site/'>Сайты</a> → <a href='{{ site.get_absolute_url }}'>{{ site.host }}</a> → <a href='/site/{{ site.host }}/add-query/'>Добавить запрос</a>
{% endblock %}

{% block title %}Добавить запрос{% endblock %}

{% block h1 %}Добавить запрос{% endblock %}

{% block content %}
    <div class="container-fluid">
    <div class="row-fluid adjust">
    {% spaceless %}
        <script src='{{ MEDIA_URL }}js/jquery.autocomplete.min.js' type='text/javascript'></script>

        <form method='post' action='.'>{% csrf_token %}
            <table  cellpadding='0' cellspacing='0'>
                {{ form.as_p }}
                <tr><td></td><td><button type='submit' class="btn
                btn-success">Добавить</button></td></tr>
            </table>
        </form>

        <script>
            $("#id_region_str").autocomplete('/regions/ac/', {'minChars':2});
        </script>

<p class="helptext">*Обновление позиций и других данных происходит раз в сутки.</p>
    {% endspaceless %}





    </div>
    </div>
{% endblock %}

sites2check/templates/add_site_bulk.html
{% extends 'base.html' %}


{% block path %}
	<a href='/'>Главная</a> → <a href='/site/'>Сайты</a> → <a href='/site/add/'>Добавить сайты</a> 
{% endblock %}


{% block title %}Добавление сайтов{% endblock %}

{% block h1 %}Добавление сайтов{% endblock %}

{% block content %}

        <div class="container-fluid">
    <div class="row-fluid adjust">
{% spaceless %}


<form method='post' action='.'>{% csrf_token %}

    Сайты:<br />
    {{ form.sites }}<br/>
    <button type='submit' class="btn btn-success">Добавить</button>

</form>
<p class="helptext">*По одному сайту на каждую строку</p>
<script>
$('#id_sites').css('width', '600px');
</script>

{% endspaceless %}
    </div>
    </div>
{% endblock %}

sites2check/templates/positions_guest.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Позиции сайта {{ site.host }}</title>
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/style.css" />
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/tableSorting/demo_table.css" />
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/jquery.autocomplete.css" />
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}galleryscript/skin-white/skin.css" />
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/redmond/jquery-ui-1.8.custom.css" />

<script src='{{ MEDIA_URL }}js/jquery.js'></script>
<script src='{{ MEDIA_URL }}js/jquery.dataTables.min.js'></script>
<script src='{{ MEDIA_URL }}js/jquery.fadetoggle.js'></script>
<script src='{{ MEDIA_URL }}galleryscript/wpzgallery.js'></script>
<script src='{{ MEDIA_URL }}js/jquery-ui-1.8.custom.min.js'></script>
<script src='{{ MEDIA_URL }}js/flot/jquery.flot.js'></script>

{% load pagination %}

    {% comment %}
{% load comments %}
{% endcomment %}
{% load sub %}


<script type='text/javascript'>
    $(document).ready(function(){
		WP('view_help').newwin();
		$('#positions_table').dataTable({
				"bStateSave": true,
				"iCookieDuration": 60*60*24*30,
				"bPaginate": false,
				"bLengthChange": true,
				"bFilter": true,
				"bSort": true,
				"bInfo": false,
				"bAutoWidth": false
		});
    });
	function showHelp(hint_id) {
		WP('view_help').param({ html:'<iframe id="iframe_view_help" width="600" height="400" src="http://localhost:8000/hint/'+hint_id+'/" frameborder="no"></iframe>', dragable:false }).show();
	}
</script>

</head>

<body>

{% spaceless %}

<h1 style='text-align:center; margin:20px; border:0; font-size:24px'>{{ site.host|upper }}</h1>

<h2>Диапазон дат <a href='#' onclick="showHelp(1); return false;" class='help1'><img src='{{ MEDIA_URL }}icons/help_min.png' /></a></h2>
<div style="text-align:center">
	<form method='GET' action='.'>
		<ul class='formlist1'>
			{{ form.as_ul }}
			<li><button type='submit'>Применить</button></li>
		</ul>
	</form>
</div>

<script type="text/javascript">
	jQuery(function() {
		jQuery("#id_date_from").datepicker({ dateFormat: 'dd/mm/yy' });
		jQuery("#id_date_to").datepicker({ dateFormat: 'dd/mm/yy' });
	});
</script>



<h2>Эффективные показы за выбранный период <a href='#' onclick="showHelp(2); return false;" class='help1'><img src='{{ MEDIA_URL }}icons/help_min.png' /></a></h2>
<p align='center'>Показы: {{ effective_shows }}, Дней: {{ total_days }}</p>



<h2>Показатели сайта <a href='#' onclick="showHelp(3); return false;" class='help1'><img src='{{ MEDIA_URL }}icons/help_min.png' /></a></h2>

<table class='table8' cellpadding='0' cellspacing='0'>
	<tr>
		<th>Индексация Яндекс</th><th class='table_row1'>Индексация Google</th><th class='table_row1'>ТИЦ</th><th class='table_row1'>PR</th><th class='table_row1'>Бэклинки</th>
	</tr>
	<tr>
		<td>
			{{ indexed_yandex.from.indexed }} → {{ indexed_yandex.to.indexed }}
			{% if indexed_yandex.to.indexed != indexed_yandex.from.indexed %}
				{% if indexed_yandex.to.indexed != None and indexed_yandex.from.indexed != None %}
						{% if indexed_yandex.to.indexed > indexed_yandex.from.indexed %}
							(<span class='moving_green'>+{{ indexed_yandex.to.indexed|sub:indexed_yandex.from.indexed|floatformat }} <img src='{{ MEDIA_URL }}up.png' class='arrow1' /></span>)
						{% endif %}
						{% if indexed_yandex.to.indexed < indexed_yandex.from.indexed %}
							(<span class='moving_red'>{{ indexed_yandex.to.indexed|sub:indexed_yandex.from.indexed|floatformat }} <img src='{{ MEDIA_URL }}down.png' class='arrow1' /></span>)
						{% endif %}
				{% endif %}
			{% endif %}
		</td>
		<td class='table_row1'>
			{{ indexed_google.from.indexed }} → {{ indexed_google.to.indexed }}
			{% if indexed_google.to.indexed != indexed_google.from.indexed %}
				{% if indexed_google.to.indexed != None and indexed_google.from.indexed != None %}
						{% if indexed_google.to.indexed > indexed_google.from.indexed %}
							(<span class='moving_green'>+{{ indexed_google.to.indexed|sub:indexed_google.from.indexed|floatformat }} <img src='{{ MEDIA_URL }}up.png' class='arrow1' /></span>)
						{% endif %}
						{% if indexed_google.to.indexed < indexed_google.from.indexed %}
							(<span class='moving_red'>{{ indexed_google.to.indexed|sub:indexed_google.from.indexed|floatformat }} <img src='{{ MEDIA_URL }}down.png' class='arrow1' /></span>)
						{% endif %}
				{% endif %}
			{% endif %}
		</td>
		<td class='table_row1'>
			{{ tic.from.tic}} → {{ tic.to.tic }}
			{% if tic.to.tic != tic.from.tic %}
				{% if tic.to.tic != None and tic.from.tic != None %}
						{% if tic.to.tic > tic.from.tic %}
							(<span class='moving_green'>+{{ tic.to.tic|sub:tic.from.tic|floatformat }} <img src='{{ MEDIA_URL }}up.png' class='arrow1' /></span>)
						{% endif %}
						{% if tic.to.tic < tic.from.tic %}
							(<span class='moving_red'>{{ tic.to.tic|sub:tic.from.tic|floatformat }} <img src='{{ MEDIA_URL }}down.png' class='arrow1' /></span>)
						{% endif %}
				{% endif %}
			{% endif %}
		</td>
		<td class='table_row1'>
			{{ pr.from.pr }} → {{ pr.to.pr }}
			{% if pr.to.pr != pr.from.pr %}
				{% if pr.to.pr != None and pr.from.pr != None %}
						{% if pr.to.pr > pr.from.pr %}
							(<span class='moving_green'>+{{ pr.to.pr|sub:pr.from.pr|floatformat }} <img src='{{ MEDIA_URL }}up.png' class='arrow1' /></span>)
						{% endif %}
						{% if pr.to.pr < pr.from.pr %}
							(<span class='moving_red'>{{ pr.to.pr|sub:pr.frompr|floatformat }} <img src='{{ MEDIA_URL }}down.png' class='arrow1' /></span>)
						{% endif %}
				{% endif %}
			{% endif %}
		</td>
		<td class='table_row1'>
			{{ site.site_backlinks.backlinks }}
		</td>
	</tr>
</table>



<h2>Позиции сайта</h2>

<p align='center'>
	<a href='/site/{{ site.host }}/guest-{{ site.getHashPass }}/xls/?date_from={{ date_from|date:"d/m/Y" }}&date_to={{ date_to|date:"d/m/Y" }}' target='_blank' style='text-decoration:none'><img src='{{ MEDIA_URL }}icons/xls.png' width='25' style='border:0; position:relative; top:6px' /> Экспорт позиций в Excel</a>
</p>


<h2>Поисковые запросы <a href='#' onclick="showHelp(5); return false;" class='help1'><img src='{{ MEDIA_URL }}icons/help_min.png' /></a></h2>

<table class='table1' cellpadding='0' cellspacing='0' id='positions_table'>
	<thead>
    <tr>
        <th>Запрос</th>
        <th class='table_row1'>Геотаргетинг <img src='{{ MEDIA_URL }}icons/yandex.gif' class='arrow1' /></th>
		<th class='table_row1'>Геотаргетинг <img src='{{ MEDIA_URL }}icons/google.gif' class='arrow1' /></th>
		<th class='table_row1'>Популярность (Wordstat)</th>
        <th class='table_row1'>Позиция <img src='{{ MEDIA_URL }}icons/yandex.gif' class='arrow1' /></th>
        <th class='table_row1'>Позиция <img src='{{ MEDIA_URL }}icons/google.gif' class='arrow1' /></th>
    </tr>
	</thead>
	<tbody>
    {% for query, pos_dict in queries_list %}
    <tr id='query_tr_{{ query.pk }}'>
        <td>
			{% if query.hilite_color %}
				<span style='color: {{ query.hilite_color }}'>{{ query.query }}</span>
			{% else %}
				{{ query.query }}
			{% endif %}
		</td>
        <td class='table_row1'>
			{% if query.region %}
				{{ query.region.title_ru }}
			{% endif %}
        </td>
        <td class='table_row1'>
			{% if query.google_region %}
				{{ query.google_region.title_ru }}
			{% endif %}
        </td>
		<td class='table_row1'>{{ query.wordstat_popularity }}</td>
        <td class='table_row1'>
        	{% if pos_dict.yandex_from.position >= 999 %}
				<i>не найден</i>
			{% else %}
				{{ pos_dict.yandex_from.position }}
			{% endif %}
			→
        	{% if pos_dict.yandex_to.position >= 999 %}
				<i>не найден</i>
			{% else %}
				{{ pos_dict.yandex_to.position }}
			{% endif %}

			{% if pos_dict.yandex_from.position != pos_dict.yandex_to.position %}
				{% if pos_dict.yandex_from.position != None and pos_dict.yandex_to.position != None %}
						{% if pos_dict.yandex_from.position > pos_dict.yandex_to.position %}
							(<span class='moving_green'>{{ pos_dict.yandex_to.position|sub:pos_dict.yandex_from.position|floatformat }} <img src='{{ MEDIA_URL }}up.png' class='arrow1' /></span>)
						{% endif %}
						{% if pos_dict.yandex_from.position < pos_dict.yandex_to.position %}
							(<span class='moving_red'>+{{ pos_dict.yandex_to.position|sub:pos_dict.yandex_from.position|floatformat }} <img src='{{ MEDIA_URL }}down.png' class='arrow1' /></span>)
						{% endif %}
				{% endif %}
			{% endif %}
		</td>
        <td class='table_row1'>
			{% if pos_dict.google_from.position >= 999 %}
			    <i>не найден</i>
			{% else %}
			    {{ pos_dict.google_from.position }}
			{% endif %}
			→
			{% if pos_dict.google_to.position >= 999 %}
			    <i>не найден</i>
			{% else %}
			    {{ pos_dict.google_to.position }}
			{% endif %}

			{% if pos_dict.google_from.position != pos_dict.google_to.position %}
				{% if pos_dict.google_from.position != None and pos_dict.google_to.position != None %}
						{% if pos_dict.google_from.position > pos_dict.google_to.position %}
							(<span class='moving_green'>{{ pos_dict.google_to.position|sub:pos_dict.google_from.position|floatformat }} <img src='{{ MEDIA_URL }}up.png' class='arrow1' /></span>)
						{% endif %}
						{% if pos_dict.google_from.position < pos_dict.google_to.position %}
							(<span class='moving_red'>+{{ pos_dict.google_to.position|sub:pos_dict.google_from.position|floatformat }} <img src='{{ MEDIA_URL }}down.png' class='arrow1' /></span>)
						{% endif %}
				{% endif %}
			{% endif %}
		</td>
    </tr>
    {% endfor %}
	</tbody>
</table>

<p style='margin:40px auto 0 auto; text-align:center; font-size:10px; color:#777'>
	Количество поисковых запросов: {{ queries_list|length }}. Время генерации страницы: {{ gen_time.seconds }} сек.
</p>

{% endspaceless %}


{% if 'localhost' not in request.get_host %}
	<script type="text/javascript">
	var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
	document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
	</script>
	<script type="text/javascript">
	try {
	var pageTracker = _gat._getTracker("UA-3972792-16");
	pageTracker._trackPageview();
	} catch(err) {}</script>
{% endif %}


{% comment %}
{% include 'template_debug.html' %}
{% endcomment %}
</body>
</html>

sites2check/templates/select_dates.html
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/style.css" />



{% if message %}
	<p class='message0'>{{ message|safe }}</p>
{% endif %}

<form method='POST' action='.' enctype="multipart/form-data">{% csrf_token %}
<table>
	{{ form.as_table }}
	<tr>
		<td></td><td><button type='submit'>Экспорт</button></td>
	</tr>
</table>
</form>